version: '3.8'
services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "${HOME}/data/DB:/var/lib/mysql"
    networks:
      - net2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD:   ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER:  ${MARIADB_USER}
      MARIADB_PASSWORD:  ${MARIADB_PASSWORD}
    
networks:
  net1:
  net2:
